name: "Deploy: Cigweld ams Dev"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
        
      - name: Rsync files
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude=".git/" --exclude=".gitignore" --exclude=".github/" --exclude="db/" --exclude="html/Users/vendor/" 
          remote_host: ${{secrets.DO_HOST_DEV}}
          remote_user: ${{secrets.SSH_USERNAME_DEV}}
          remote_key: ${{secrets.SSH_KEY_DEV}}
          remote_path: /home/cigweld/ams
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DO_HOST_DEV}}
          username: ${{secrets.SSH_USERNAME_DEV}}
          key: ${{secrets.SSH_KEY_DEV}}
          script: |
            cd /home/cigweld/ams
            chmod -R 777 ./html
            docker exec --workdir /var/www/html/Users AMSWEB composer install
